### ISSUE TITLE
Help for MCZ DOC (Maestro) new config 

### ISSUE THREAD

**Issue by fastenspy** [securechicken/homebridge-micronova-agua-iot-stove#6]
Hello,

I am looking to configure my MCZ DOC pellet. I don't have a login and password in the app. Is it still possible?

Homebridge Version: Raspberry Pi - UI: 1.3.4 / Node.js v14.16.0 / NPM: v6.14.11
Plugin version: 1.0.0 
Stove brand/mobile app name: MCZ DOC / MCZ MAESTRO (iOS)

Thanks a lot

**Comment by securechicken** [comment]
Hi @fastenspy,

I don't know, don't have such a stove model to test with; but as far as I know; Micronova API accesses are authenticated, so somehow require a login and secret - the plugin does in any case, and won't work without them.

Do you actually have a Micronova "Agua IOT" module attached to your stove?
How did you register the module with the app/on the Internet? Didn't you need a login/password to register?
Are you able to proceed with network packets capture between your iOS device and Internet servers when you use the official app ?

**Comment by securechicken** [comment]
Dear @fastenspy, any follow-up from your side?

**Comment by securechicken** [comment]
Closed due to lack of information to assess.
