### ISSUE TITLE
HTTP request failed

### ISSUE THREAD

**Issue by Slavitacus** [securechicken/homebridge-micronova-agua-iot-stove#8]
## Environment and Input

|Item|Your information|
|---|---|
|**Homebridge Version**|v1.5.0|
|**Plugin version**|v1.1.0|
|**Stove brand/mobile app name**|Jolly Mec Wi Fi|
|**iOS version**|15.5|

Hello,

The Plugin doesn't works anymore, I have this error message:

_sendAPIRequest HTTP request failed. Retrying... Reason: _sendAPIRequest got 401 status, not logged-in or token expired

**Comment by gzeel** [comment]
I'm having the same problem.. any updates on this issue?

**Comment by securechicken** [comment]
Unfortunately I'm not using Homebridge anymore, and as a consequence does not maintain the plugin - which can still be forked and updated elsewhere if need be.
Should such issue happen, and restart of the plugin container in Homebridge would supposedly temporarily fix it (it's likely an authentication token expired before it was expected to expire). Then modifying delays in the code is probably required to fix further.
