### ISSUE TITLE
Nordic Fire stove visible but not reacting

### ISSUE THREAD

**Issue by xxAntonyxx** [securechicken/homebridge-micronova-agua-iot-stove#9]
my Nordic Fire stove seems to be connected though the plugin with the Nordic Fire 2.0 account and is available in Homekit. In Homekit the stove is unavailable (when run out of pellets or power turned completely off). But I can not operate the stove. The current temperature shows  0,0 and status is off. When turning it on, status changes to heating to (null) but stove is not reacting.
Any ideas what is wrong?

**Comment by securechicken** [comment]
Dear @xxAntonyxx, unfortunately I'm not using Homebridge anymore, and as a consequence does not maintain the plugin - which can still be forked and updated elsewhere if need be.
The Nordic Fire brand was however not marked as supported, some investigations are required to confirm their official app indeed use the Micronova API, and then check how it is used for this specific brand / specific stove models.
